### ISSUE TITLE
haproxy.cfg validation warnings spamming console

### ISSUE THREAD

**Issue by paulrobello** [vfarcic/docker-flow-proxy#376]
Starting in the last couple of days, I am getting the following in the console every second.

2017/11/17 23:22:36 Validating configuration
[WARNING] 320/232236 (6746) : parsing [/cfg/haproxy.cfg:63] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
Configuration file is valid
2017/11/17 23:22:36 Config validation failed. Will try again...

I am also getting the following error trying to hit many of my proxied containers
"Docker Flow Proxy: 503 Service Unavailable"

**Comment by vfarcic** [comment]
Can you post the stack you are using? That should help me replicate the issue.

**Comment by paulrobello** [comment]
I have seen the issue present with even with just the proxy stack
I have 3 nodes all are managers lenny,lenny2,lenny3
The network parweb is public and parint is internal both are encrypted overlay networks

This is my proxy stack
-------------------------------------
version: "3"

services:
  proxy:
    image: vfarcic/docker-flow-proxy:latest
    ports:
      - 80:80
      - 443:443
#      - 8080:8080
    networks:
      - parweb
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 3s
      resources:
        limits:
          memory: 64M
          cpus: '1'

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:latest
    networks:
      - parweb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 64M
          cpus: '1'

  letsencrypt-companion:
    image: hamburml/docker-flow-letsencrypt:latest
    networks:
      - parweb
    environment:
      - DOMAIN_1=('pardev.net' 'alexa.pardev.net' 'alexa-gui.pardev.net' 'rethinkdb.pardev.net' 'portainer.pardev.net' 'grafana.pardev.net' 'regview.pardev.net')
      - CERTBOT_EMAIL=probello@gmail.com
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      labels:
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=80
      placement:
        constraints:
          - node.labels.myname == lenny3
      resources:
        limits:
          memory: 64M
          cpus: '1'
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s

networks:
  parweb:
    external: true
------------------------------------
web stack
------------------------------------
version: "3.3"
services:
  bj:
    image: pardev.net:5000/site_hosting_php_70:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s
        window: 30s
      placement:
        constraints:
          - node.labels.bj.replica == 4
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=backjacker.com,www.backjacker.com,licensing1.backjacker.com
        - com.df.port=80
    ports:
      - 80
    volumes:
      - /docker/bj/data:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=America/Los_Angeles
      - php.short_open_tag=On
      - php.asp_tags=Off
      - php.zlib.output_compression=On
      - php.zend.enable_gc=On
      - php.expose_php=Off
      - php.error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
      - php.display_errors=On
      - php.display_startup_errors=On
      - php.variables_order = "GPCS"
      - php.register_argc_argv=Off
    networks:
      - parweb
      - parint

  bj-support:
    image: pardev.net:5000/site_hosting_php_56:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s
        window: 30s
      placement:
        constraints:
          - node.labels.bj.replica == 4
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=support.backjacker.com
        - com.df.port=80
    ports:
      - 80
    volumes:
      - /docker/bj-support/data:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=America/Los_Angeles
      - php.short_open_tag=On
      - php.asp_tags=Off
      - php.zlib.output_compression=On
      - php.zend.enable_gc=On
      - php.expose_php=Off
      - php.error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
      - php.display_errors=On
      - php.display_startup_errors=On
      - php.variables_order = "GPCS"
      - php.register_argc_argv=Off
    networks:
      - parweb
      - parint

  bj-marketing:
    image: pardev.net:5000/site_hosting_php_56:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s
        window: 30s
      placement:
        constraints:
          - node.labels.bj.replica == 4
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=marketing.backjacker.com
        - com.df.port=80
    ports:
      - 80
    volumes:
      - /docker/bj-marketing/data:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=America/Los_Angeles
      - php.short_open_tag=On
      - php.asp_tags=Off
      - php.zlib.output_compression=On
      - php.zend.enable_gc=On
      - php.expose_php=Off
      - php.error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
      - php.display_errors=On
      - php.display_startup_errors=On
      - php.variables_order = "GPCS"
      - php.register_argc_argv=Off
    networks:
      - parweb
      - parint

networks:
  default:
    external:
       name: parint
  parint:
    external: true
  parweb:
    external: true

------------------------------------

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I could not find a free moment until now...

Can you post HAProxy config as well? You can get it by entering one of the DFP containers and `cat /cfg/haproxy.cfg`.

There were quite a few reports of problems with encrypted networks. Can you try without encryption and see whether the result is the same (problems persist).

What do you mean by *the network parweb is public and parint is internal*?

As a side note, there's no need to have DFP as a  `global` service.

**Comment by paulrobello** [comment]
network parint has the following flags set
        "Internal": true,
        "Attachable": true,
        "Ingress": false,
        "encrypted"

network parweb has the following flags set
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "encrypted"

This is the docker explanation of the internal flag

**Network internal mode**
By default, when you connect a container to an overlay network, Docker also connects a bridge network to it to provide external connectivity. If you want to create an externally isolated overlay network, you can specify the --internal option.

The encrypted network should be transparent to the containers, and appears to be working fine.
To un encrypted the network I would have to tear down my entire deployment. I am not ready to do that just yet.

contents of /cfg/haproxy.cfg with any passwords replaced with ****
-------------------------------------
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-keep-alive
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s


    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats uri /admin?stats
    stats auth admin:*****
frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt
    mode http

    acl url_proxy_letsencrypt-companion80_0 path_beg /.well-known/acme-challenge
    use_backend proxy_letsencrypt-companion-be80_0 if url_proxy_letsencrypt-companion80_0
    acl url_alexa-hub-gui_alexa-hub-gui8080_0 path_beg /
    acl domain_alexa-hub-gui_alexa-hub-gui8080_0 hdr_beg(host) -i alexa-gui.pardev.net
    acl is_alexa-hub-gui_alexa-hub-gui_http hdr(X-Forwarded-Proto) http
    http-request redirect scheme https if is_alexa-hub-gui_alexa-hub-gui_http url_alexa-hub-gui_alexa-hub-gui8080_0 domain_alexa-hub-gui_alexa-hub-gui8080_0
    use_backend alexa-hub-gui_alexa-hub-gui-be8080_0 if url_alexa-hub-gui_alexa-hub-gui8080_0 domain_alexa-hub-gui_alexa-hub-gui8080_0
    acl url_alexa-server-hub_alexa-server-hub8080_0 path_beg /
    acl domain_alexa-server-hub_alexa-server-hub8080_0 hdr_beg(host) -i alexa.pardev.net
    acl is_alexa-server-hub_alexa-server-hub_http hdr(X-Forwarded-Proto) http
    http-request redirect scheme https if is_alexa-server-hub_alexa-server-hub_http url_alexa-server-hub_alexa-server-hub8080_0 domain_alexa-server-hub_alexa-server-hub8080_0
    use_backend alexa-server-hub_alexa-server-hub-be8080_0 if url_alexa-server-hub_alexa-server-hub8080_0 domain_alexa-server-hub_alexa-server-hub8080_0
    acl url_db_rethinkdb18080_0 path_beg /
    acl domain_db_rethinkdb18080_0 hdr_beg(host) -i rethinkdb.pardev.net
    acl is_db_rethinkdb1_http hdr(X-Forwarded-Proto) http
    http-request redirect scheme https if is_db_rethinkdb1_http url_db_rethinkdb18080_0 domain_db_rethinkdb18080_0
    use_backend db_rethinkdb1-be8080_0 if url_db_rethinkdb18080_0 domain_db_rethinkdb18080_0
    acl url_reg_portainer9000_0 path_beg /
    acl domain_reg_portainer9000_0 hdr_beg(host) -i portainer.pardev.net
    acl is_reg_portainer_http hdr(X-Forwarded-Proto) http
    http-request redirect scheme https if is_reg_portainer_http url_reg_portainer9000_0 domain_reg_portainer9000_0
    use_backend reg_portainer-be9000_0 if url_reg_portainer9000_0 domain_reg_portainer9000_0
    acl url_reg_registry_viewer80_0 path_beg /
    acl domain_reg_registry_viewer80_0 hdr_beg(host) -i regview.pardev.net
    acl is_reg_registry_viewer_http hdr(X-Forwarded-Proto) http
    http-request redirect scheme https if is_reg_registry_viewer_http url_reg_registry_viewer80_0 domain_reg_registry_viewer80_0
    use_backend reg_registry_viewer-be80_0 if url_reg_registry_viewer80_0 domain_reg_registry_viewer80_0
    acl url_sites_bj80_0 path_beg /
    acl domain_sites_bj80_0 hdr_beg(host) -i backjacker.com www.backjacker.com licensing1.backjacker.com
    use_backend sites_bj-be80_0 if url_sites_bj80_0 domain_sites_bj80_0
    acl url_sites_bj-marketing80_0 path_beg /
    acl domain_sites_bj-marketing80_0 hdr_beg(host) -i marketing.backjacker.com
    use_backend sites_bj-marketing-be80_0 if url_sites_bj-marketing80_0 domain_sites_bj-marketing80_0
    acl url_sites_bj-support80_0 path_beg /
    acl domain_sites_bj-support80_0 hdr_beg(host) -i support.backjacker.com
    use_backend sites_bj-support-be80_0 if url_sites_bj-support80_0 domain_sites_bj-support80_0





















backend alexa-hub-gui_alexa-hub-gui-be8080_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server alexa-hub-gui_alexa-hub-gui alexa-hub-gui_alexa-hub-gui:8080


backend alexa-server-hub_alexa-server-hub-be8080_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server alexa-server-hub_alexa-server-hub alexa-server-hub_alexa-server-hub:8080

userlist db_rethinkdb1Users
    user admin insecure-password *****


backend db_rethinkdb1-be8080_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server db_rethinkdb1 db_rethinkdb1:8080
    acl db_rethinkdb1UsersAcl http_auth(db_rethinkdb1Users)
    http-request auth realm db_rethinkdb1Realm if !db_rethinkdb1UsersAcl
    http-request del-header Authorization


backend proxy_letsencrypt-companion-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server proxy_letsencrypt-companion proxy_letsencrypt-companion:80


backend reg_portainer-be9000_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server reg_portainer reg_portainer:9000

userlist reg_registry_viewerUsers
    user admin insecure-password *****


backend reg_registry_viewer-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server reg_registry_viewer reg_registry_viewer:80
    acl reg_registry_viewerUsersAcl http_auth(reg_registry_viewerUsers)
    http-request auth realm reg_registry_viewerRealm if !reg_registry_viewerUsersAcl
    http-request del-header Authorization


backend sites_bj-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server sites_bj sites_bj:80


backend sites_bj-marketing-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server sites_bj-marketing sites_bj-marketing:80


backend sites_bj-support-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server sites_bj-support sites_bj-support:80

**Comment by paulrobello** [comment]
I cleaned up my stacks and am no longer getting the original error.
I found that commenting out "com.df.redirectWhenHttpProto=true" from all my configs resolved all my "Config validation failed. Will try again..." errors

**Comment by vfarcic** [comment]
There are a few problems with the newly added `redirectWhenHttpProto` parameter. It's been temporarily disabled in the tag `vfarcic/docker-flow-proxy:17.11.24-67` until we fix it.

**Comment by vfarcic** [comment]
Can you please try out the latest tag `vfarcic/docker-flow-proxy:17.12.02-72`? The problem should be resolved.

**Comment by paulrobello** [comment]
sorry i took so long to get back to this.
Should i try the latest tag of 17.12.17-87 ?

**Comment by paulrobello** [comment]
using com.df.redirectWhenHttpProto=true now causes a TOO MANY REDIRECTS error.
using com.df.httpsOnly=true seems to work perfectly

**Comment by paulrobello** [comment]
still getting too many redirects with vfarcic/docker-flow-proxy:issue-376

**Comment by vfarcic** [comment]
I could not find the problem in the config.

```
http-request redirect scheme https if is_alexa-hub-gui_alexa-hub-gui_http url_alexa-hub-gui_alexa-hub-gui8080_0 domain_alexa-hub-gui_alexa-hub-gui8080_0
```

...translates to _redirect to `https` protocol if `X-Forwarded-Proto` is present in header and the protocol is `http` and path starts with `/` and the domain is `alexa-gui.pardev.net`_.

I'm sure that there is a problem (in DFP or in the external proxy/LB) but I'm failing to spot it. The config you posted is with `redirectWhenHttpProto` only (without `httpsOnly`).

The latest failure is with the config that has both? If it's with both, I think I know what the issue is but I'd need you to post the config to confirm that. The one from above is without `httpsOnly`?

What would help a lot if you could experient with changes to the config. You can modify it and send a [reload request](http://proxy.dockerflow.com/usage/#reload) to apply the changes. That would fast-track the resolution since I'd know which part of the config is causing problems.

**Comment by paulrobello** [comment]
I was using only the redirectWhenHttpProto when I encountered problems.
As soon as I switched it to httpsOnly everything worked fine, clients are redirected from http to https.

**Comment by vfarcic** [comment]
My best guess is that your external LB is non injecting `X-Forwarded-Proto`. Normally, `httpsOnly` is the preferable parameter. `X-Forwarded-Proto` is mostly for those cases when requests that are meant to be HTTPS are still sent as HTTP. Since `httpsOnly` works for you, we can probably consider this issue closed.
